//
//  ContactViewInteractor.swift
//  Clean-swift-article
//
//  Created by Anton Marunko on 30/05/2018.
//  Copyright (c) 2018 exyte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactViewBusinessLogic {
    func fetchContact(request: ContactView.ShowContact.Request)
}

protocol ContactViewDataStore {
    var contact: Contact? { get set }
}

final class ContactViewInteractor: ContactViewBusinessLogic, ContactViewDataStore {
    var presenter: ContactViewPresentationLogic?
    var worker = ContactViewWorker()
    var contact: Contact?

    // MARK: - ContactViewBusinessLogic

    func fetchContact(request: ContactView.ShowContact.Request) {
        let response = ContactView.ShowContact.Response(contact: contact!)
        presenter?.presentContact(response: response)
    }
}
