//
//  ContactViewPresenter.swift
//  Clean-swift-article
//
//  Created by Anton Marunko on 30/05/2018.
//  Copyright (c) 2018 exyte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactViewPresentationLogic {
    func presentContact(response: ContactView.ShowContact.Response)
}

final class ContactViewPresenter: ContactViewPresentationLogic {
    weak var viewController: ContactViewDisplayLogic?

    // MARK: - ContactViewPresentationLogic

    func presentContact(response: ContactView.ShowContact.Response) {

        let phone = PhoneFormatter.format(sourcePhoneNumber: response.contact.phone) ?? response.contact.phone

        let viewModel = ContactView.ShowContact.ViewModel(
            firstName: response.contact.firstName,
            lastName: response.contact.lastName,
            address: response.contact.address,
            phone: phone)

        viewController?.displayContact(viewModel: viewModel)
    }
}
