//
//  AddContactViewController.swift
//  Clean-swift-article
//
//  Created by Anton Marunko on 30/05/2018.
//  Copyright (c) 2018 exyte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddContactDisplayLogic: class {
    func displayContact(viewModel: AddContact.ShowContact.ViewModel)
    func displayMissingFields(viewModel: AddContact.ShowMissingFields.ViewModel)
    func displaySavedContact(viewModel: AddContact.Save.ViewModel)
}

final class AddContactViewController: UIViewController, AddContactDisplayLogic {
    var interactor: AddContactBusinessLogic?
    var router: (NSObjectProtocol & AddContactRoutingLogic & AddContactDataPassing)?

    @IBOutlet private weak var firstNameField: UITextField!
    @IBOutlet private weak var lastNameField: UITextField!
    @IBOutlet private weak var phoneField: UITextField!
    @IBOutlet private weak var addressField: UITextField!

    // MARK: Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        AddContactConfigurator.sharedInstance.configure(self)
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        let request = AddContact.ShowContact.Request()
        interactor?.showContact(request: request)
    }

    // MARK: - Interactor requests

    func fetchContactData() {
        let request = AddContact.ShowContact.Request()
        interactor?.showContact(request: request)
    }

    // MARK: - IBActions

    @IBAction func save(_ sender: Any) {
        let request = AddContact.Save.Request(
            firstNameText: firstNameField.text,
            lastNameText: lastNameField.text,
            phoneText: phoneField.text,
            adddress: addressField.text)

        interactor?.saveContact(request: request)
    }

    // MARK: - AddContactDisplayLogic

    func displayContact(viewModel: AddContact.ShowContact.ViewModel) {
        firstNameField.text = viewModel.firstName
        lastNameField.text = viewModel.lastName
        addressField.text = viewModel.address
        phoneField.text = viewModel.phone
    }

    func displayMissingFields(viewModel: AddContact.ShowMissingFields.ViewModel) {
        showOkAlert(title: .none, message: viewModel.text)
    }

    func displaySavedContact(viewModel: AddContact.Save.ViewModel) {
        router?.routeToContactList()
    }

    // MARK: -

    private func showOkAlert(title: String?, message: String?) {
        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)

        let okAction = UIAlertAction(title: NSLocalizedString("Ok", comment: ""), style: .default, handler: .none)

        alert.addAction(okAction)

        present(alert, animated: true, completion: .none)
    }
}
