//
//  AddContactRouter.swift
//  Clean-swift-article
//
//  Created by Anton Marunko on 30/05/2018.
//  Copyright (c) 2018 exyte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddContactRoutingLogic {
    func routeToContactList()
}

protocol AddContactDataPassing {
    var dataStore: AddContactDataStore? { get }
}

final class AddContactRouter: NSObject, AddContactRoutingLogic, AddContactDataPassing {
    weak var viewController: AddContactViewController?
    var dataStore: AddContactDataStore?

    // MARK: - Routing

    func routeToContactList() {

        viewController?.navigationController?.popViewController(animated: true)
    }

    func routeToContactView(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ContactViewViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToViewContact(source: dataStore!, destination: &destinationDS)
        } else {
            let index = viewController!.navigationController!.viewControllers.count - 2
            let destinationVC = viewController?.navigationController?.viewControllers[index] as! ContactViewViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToViewContact(source: dataStore!, destination: &destinationDS)
            navigateToViewContact(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: - Navigation

    func navigateToViewContact(source: AddContactViewController, destination: ContactViewViewController) {
        source.navigationController?.popViewController(animated: true)
    }

    // MARK: - Passing data

    func passDataToViewContact(source: AddContactDataStore, destination: inout ContactViewDataStore) {
        destination.contact = source.contact
    }
}
