//
//  AddContactModels.swift
//  Clean-swift-article
//
//  Created by Anton Marunko on 30/05/2018.
//  Copyright (c) 2018 exyte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddContact {
    // MARK: Use cases

    enum ShowContact {
        struct Request {
        }

        struct Response {
            let contact: Contact
        }

        struct ViewModel {
            let firstName: String
            let lastName: String
            let address: String
            let phone: String
        }
    }

    enum ShowMissingFields {
        struct Response {
            let text: String
        }

        struct ViewModel {
            let text: String
        }
    }

    enum Save {
        struct Request {
            let firstNameText: String?
            let lastNameText: String?
            let phoneText: String?
            let adddress: String?
        }

        struct Response {
        }

        struct ViewModel {
        }
    }
}
