//
//  ContactListInteractor.swift
//  Clean-swift-article
//
//  Created by Anton Marunko on 25/05/2018.
//  Copyright (c) 2018 exyte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactListBusinessLogic {
    func showContacts(request: ContactList.ShowContacts.Request)
}

protocol ContactListDataStore {
    var contacts: [Contact]? { get }
}

final class ContactListInteractor: ContactListBusinessLogic, ContactListDataStore {
    var presenter: ContactListPresentationLogic?
    var worker = ContactListWorker()
    var contacts: [Contact]?

    // MARK: - ContactListBusinessLogic

    func showContacts(request: ContactList.ShowContacts.Request) {
        let contacts = worker.getContacts()
        self.contacts = contacts
        let response = ContactList.ShowContacts.Response(contacts: contacts)
        presenter?.presentContacts(response: response)
    }
}
