//
//  ContactListPresenter.swift
//  Clean-swift-article
//
//  Created by Anton Marunko on 25/05/2018.
//  Copyright (c) 2018 exyte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactListPresentationLogic {
    func presentContacts(response: ContactList.ShowContacts.Response)
}

final class ContactListPresenter: ContactListPresentationLogic {
    weak var viewController: ContactListDisplayLogic?

    // MARK: - ContactListPresentationLogic

    func presentContacts(response: ContactList.ShowContacts.Response) {
        let mapped = response.contacts.map {
            ContactList
                .ShowContacts
                .ViewModel
                .DisplayedContact(firstName: $0.firstName.uppercaseFirst,
                                  lastName: $0.lastName.uppercaseFirst)
        }

        let viewModel = ContactList.ShowContacts.ViewModel(displayedContacts: mapped)
        viewController?.displayContacts(viewModel: viewModel)
    }
}
