//
//  ContactListViewController.swift
//  Clean-swift-article
//
//  Created by Anton Marunko on 25/05/2018.
//  Copyright (c) 2018 exyte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContactListDisplayLogic: class {
    func displayContacts(viewModel: ContactList.ShowContacts.ViewModel)
}

final class ContactListViewController: UITableViewController, ContactListDisplayLogic {
    var interactor: ContactListBusinessLogic?
    var router: (NSObjectProtocol & ContactListRoutingLogic & ContactListDataPassing)?

    var displayedContacts = [ContactList.ShowContacts.ViewModel.DisplayedContact]()

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: - Setup

    private func setup() {
        let viewController = self
        let interactor = ContactListInteractor()
        let presenter = ContactListPresenter()
        let router = ContactListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: - Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        fetchContacts()
    }

    // MARK: - Private

    private func fetchContacts() {
        let request = ContactList.ShowContacts.Request()
        interactor?.showContacts(request: request)
    }

    // MARK: - ContactListDisplayLogic

    func displayContacts(viewModel: ContactList.ShowContacts.ViewModel) {
        displayedContacts = viewModel.displayedContacts
        tableView.reloadData()
    }

    // MARK: - UITableDataSource

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return displayedContacts.count
    }

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = tableView.dequeueReusableCell(withIdentifier: "contcactListCell") {

            let contact = displayedContacts[indexPath.row]

            cell.textLabel?.text = contact.fullName

            return cell
        }

        return UITableViewCell()
    }
}
