//
//  ContactListModels.swift
//  Clean-swift-article
//
//  Created by Anton Marunko on 25/05/2018.
//  Copyright (c) 2018 exyte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ContactList {
    // MARK: Use cases

    enum ShowContacts {
        struct Request {
        }

        struct Response {
            var contacts: [Contact]
        }

        struct ViewModel {
            struct DisplayedContact {
                let firstName: String
                let lastName: String

                var fullName: String {
                    return firstName + " " + lastName
                }
            }

            var displayedContacts: [DisplayedContact]
        }
    }

    enum AddContact {
        struct Request {
        }

        struct Response {
        }

        struct ViewModel {
        }
    }
}
